# build netcat runner binaries
FROM golang:1.18-alpine AS builder-netcat

ENV PKG_NAME=github.com/Tal-or/rps-debug
ENV PKG_PATH=/go/src/$PKG_NAME

RUN mkdir -p $PKG_PATH

COPY . $PKG_PATH/
WORKDIR $PKG_PATH
RUN go build -mod=vendor -o /netcat-runner netcat/main.go


FROM centos:7

RUN curl -L https://forensics.cert.org/cert-forensics-tools-release-el7.rpm -o cert-forensics-tools-release-el7.rpm && \
    rpm -Uvh cert-forensics-tools-release*rpm && \
    yum --enablerepo=forensics install -y musl-libc iproute ethtool ping nc

COPY --from=builder-netcat /netcat-runner /usr/bin/netcat-runner

ENV SUITES_PATH=/usr/bin/

CMD ["/usr/bin/netcat-runner"]